#This is a samply config file.  Create a file named conf.py,in this directory, and decalre the following variables there.
#DO NOT EDIT THIS FILE.  This file is not read for config changes
APPURL = ('http://foo/bar',) # The path which points to "alipi" directory. 
JQUERYURL = ('http://foo.jquery',) #URL for jquery.
PASSWD = ('password',)
BLOGURL = ('http://something.blogspot.com',)
EMAIL = ('johnDoe@gmail.com',)
DEPLOYURL = ('http://127.0.0.1:5000/',)
