#This is a samply config file.  Create a file named conf.py,in this directory, and decalre the following variables there.
#DO NOT EDIT THIS FILE.  This file is not read for config changes
APPURL = ('http://y.a11y.in',) # The path which points to "alipi" directory.
JQUERYURL = ('http://foo.jquery',) #URL for jquery.
JQUERYUI = ('http://y.a11y.in/apis',) #URL for loading jQuery UI theme and widgets
JQUERYCSS = ('http://y.a11y.in/apis',) #URL for loading custom jQuery CSS
PASSWD = ('password',) #Deprecated
BLOGURL = ('http://something.blogspot.com',) #Temporarily deprecated.
EMAIL = ('johnDoe@gmail.com',) #Deprecated
DEPLOYURL = ('http://y.a11y.in/app',) #URL pointing to the application
DBNAME = ('test',) #mySQL db for holding a list of language and location
DBPASSWD = ('admin',) #mySQL password
DBUSRNAME = ('sql_password',) #mySQL user with read access to the DBNAME
DBHOST = ('localhost',)
MONGODB = ('alipi',) #Name of the database in MongoDB
SWEETURL = ('http://demo.swtr.us',) #URL to a sweet store
SWEET_STORE_ADD = ("http://demo.swtr.us/add",) #The specific API endpoint for submitting sweets
